var child = [
  { 'dupe': false, 'type': 32, 'name': 'confirmregister.php', 'dir': 'c0', 'linked': 5, 'url': 'http://localhost:8008/confirm.php/confirmregister.php', 'fetched': true, 'code': 302, 'len': 1089, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 0, 0, 0, 5, 0 ], 'sig': 0xc32f3a2a },
  { 'dupe': false, 'type': 32, 'name': 'historia.php', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost:8008/confirm.php/historia.php', 'fetched': true, 'code': 302, 'len': 1089, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'login.php', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost:8008/confirm.php/login.php', 'fetched': true, 'code': 302, 'len': 1089, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'logout.php', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost:8008/confirm.php/logout.php', 'fetched': true, 'code': 302, 'len': 1089, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'przelew.php', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost:8008/confirm.php/przelew.php', 'fetched': true, 'code': 302, 'len': 1089, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': false, 'type': 64, 'name': 'account=1', 'dir': 'c5', 'linked': 5, 'url': 'http://localhost:8008/confirm.php DATA:name=Smith&account=1&amount=1&address=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 1121, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 1, 0 ], 'sig': 0x801c694 },
  { 'dupe': false, 'type': 64, 'name': 'address=1', 'dir': 'c6', 'linked': 5, 'url': 'http://localhost:8008/confirm.php DATA:name=Smith&account=1&amount=1&address=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 1121, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 1, 0 ], 'sig': 0x801c694 },
  { 'dupe': false, 'type': 64, 'name': 'amount=1', 'dir': 'c7', 'linked': 5, 'url': 'http://localhost:8008/confirm.php DATA:name=Smith&account=1&amount=1&address=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 1121, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 1, 0 ], 'sig': 0x801c694 },
  { 'dupe': false, 'type': 64, 'name': 'name=Smith', 'dir': 'c8', 'linked': 5, 'url': 'http://localhost:8008/confirm.php DATA:name=Smith&account=1&amount=1&address=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 1121, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 1, 0 ], 'sig': 0x801c694 },
  { 'dupe': false, 'type': 64, 'name': 'title=skipfish', 'dir': 'c9', 'linked': 5, 'url': 'http://localhost:8008/confirm.php DATA:name=Smith&account=1&amount=1&address=1&title=skipfish', 'fetched': true, 'code': 302, 'len': 1121, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 1, 0 ], 'sig': 0x801c694 }
];
