var child = [
  { 'dupe': false, 'type': 16, 'name': 'announcement.sfish', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/announcement.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'archive.sfish', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/archive.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'avatars.sfish', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/avatars.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'b.sfish', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/b.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'changed.sfish', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/changed.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'cocoon.sfish', 'dir': 'c5', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/cocoon.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'de.sfish', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/de.sfish', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'login.php', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/login.php', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'przelew.php', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/przelew.php', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
];
