var child = [
  { 'dupe': false, 'type': 8, 'name': 'announcement.sfish', 'dir': 'c0', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/announcement.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 1, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'archive.sfish', 'dir': 'c1', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/archive.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'avatars.sfish', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/avatars.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': false, 'type': 8, 'name': 'avatars.sfish.xls', 'dir': 'c3', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/avatars.sfish.xls', 'fetched': true, 'code': 200, 'len': 1073, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'b.sfish', 'dir': 'c4', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/b.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'changed.sfish', 'dir': 'c5', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/changed.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'cocoon.sfish', 'dir': 'c6', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/cocoon.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'de.sfish', 'dir': 'c7', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/de.sfish', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'historia.php', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/historia.php', 'fetched': true, 'code': 200, 'len': 1078, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'login.php', 'dir': 'c9', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/login.php', 'fetched': true, 'code': 200, 'len': 1078, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': true, 'type': 8, 'name': 'przelew.php', 'dir': 'c10', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/przelew.php', 'fetched': true, 'code': 200, 'len': 1076, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff515ae },
  { 'dupe': false, 'type': 8, 'name': 'przelewregister.php', 'dir': 'c11', 'linked': 5, 'url': 'http://localhost:8008/przelew.php/przelewregister.php', 'fetched': true, 'code': 200, 'len': 1078, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 0, 1, 6, 0, 0 ], 'sig': 0xc305d07b },
  { 'dupe': false, 'type': 16, 'name': 'avatars', 'dir': 'c12', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/avatars', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'b', 'dir': 'c13', 'linked': 0, 'url': 'http://localhost:8008/przelew.php/b', 'fetched': true, 'code': 200, 'len': 1082, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 32, 'name': 'logout.php', 'dir': 'c14', 'linked': 2, 'url': 'http://localhost:8008/przelew.php/logout.php', 'fetched': true, 'code': 302, 'len': 921, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': false, 'type': 64, 'name': 'error=account', 'dir': 'c15', 'linked': 2, 'url': 'http://localhost:8008/przelew.php?error=account', 'fetched': true, 'code': 200, 'len': 1149, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0xffbe8877 }
];
